config/routes.rb
Rails.application.routes.draw do
  

  
  resources :memos
  resources :hamsters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hamster.rb
class Hamster < ApplicationRecord
    has_many :memos
end

app/controllers/hamsters_controller.rb
class HamstersController < ApplicationController
  before_action :set_hamster, only: %i[ show edit update destroy ]

  # GET /hamsters or /hamsters.json
  def index
    @hamsters = Hamster.all
  end

  # GET /hamsters/1 or /hamsters/1.json
  def show
    @newmemo  = @hamster.memos.new()
    Rails.logger.debug "shiina"
    Rails.logger.debug @newmemo
    @memos = Memo.where(hamster_id: params[:id])
  end

  # GET /hamsters/new
  def new
    @hamster = Hamster.new
  end

  # GET /hamsters/1/edit
  def edit
  end

  # POST /hamsters or /hamsters.json
  def create
    @hamster = Hamster.new(hamster_params)

    respond_to do |format|
      if @hamster.save
        format.html { redirect_to hamster_url(@hamster), notice: "Hamster was successfully created." }
        format.json { render :show, status: :created, location: @hamster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hamster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hamsters/1 or /hamsters/1.json
  def update
    respond_to do |format|
      if @hamster.update(hamster_params)
        format.html { redirect_to hamster_url(@hamster), notice: "Hamster was successfully updated." }
        format.json { render :show, status: :ok, location: @hamster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hamster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hamsters/1 or /hamsters/1.json
  def destroy
    @hamster.destroy

    respond_to do |format|
      format.html { redirect_to hamsters_url, notice: "Hamster was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hamster
      @hamster = Hamster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hamster_params
      params.require(:hamster).permit(:hamstername)
      .permit(:high, :city)
    end
end

app/helpers/hamsters_helper.rb
module HamstersHelper
end

app/views/hamsters/_form.html.erb
<%= form_with(model: hamster, local: true) do |form| %>
  <% if hamster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hamster.errors.count, "error") %> prohibited this hamster from being saved:</h2>

      <ul>
      <% hamster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hamstername %>
    <%= form.text_field :hamstername %>
  </div>

  <div class="field">
    <%= form.label :high %>
    <%= form.number_field :high %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hamsters/edit.html.erb
<h1>Editing Hamster</h1>

<%= render 'form', hamster: @hamster %>

<%= link_to 'Show', @hamster %> |
<%= link_to 'Back', hamsters_path %>

app/views/hamsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hamsters</h1>

<table>
  <thead>
    <tr>
      <th>Hamstername</th>
      <th>High</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hamsters.each do |hamster| %>
      <tr>
        <td><%= hamster.hamstername %></td>
        <td><%= hamster.high %></td>
        <td><%= hamster.city %></td>
        <td><%= link_to 'Show', hamster %></td>
        <td><%= link_to 'Edit', edit_hamster_path(hamster) %></td>
        <td><%= link_to 'Destroy', hamster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hamster', new_hamster_path %>

app/views/hamsters/new.html.erb
<h1>New Hamster</h1>

<%= render 'form', hamster: @hamster %>

<%= link_to 'Back', hamsters_path %>

app/views/hamsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hamstername:</strong>
  <%= @hamster.hamstername %>
</p>

<p>
  <strong>High:</strong>
  <%= @hamster.high %>
</p>

<p>
  <strong>City:</strong>
  <%= @hamster.city %>
</p>
<%= link_to 'Edit', edit_hamster_path(@hamster) %> |

<br /><br /><br /><br /><br /><br />
<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'memos/form', memo: @newmemo %>


<%= link_to 'Back', hamsters_path %>